### ISSUE TITLE
Level One

### ISSUE THREAD

**Issue by camerongough** [HolmesSquad/ProjectTwo#1]

**Comment by hughest8** [comment]
Level 1

• Number of  landmarks
• 1 treasure
o   Which is hidden in a landmark
• A set of traffic lights with instructions
• Single start point
• Stop at landmark with treasure
• Landmarks should have
o   Name
o   Info on if treasure hidden
• Treasure should have
o   ID
o   Name
• Lights should have
o   Reference number
o   Two settings
 Red
 Green
