### ISSUE TITLE
Level Two

### ISSUE THREAD

**Issue by camerongough** [HolmesSquad/ProjectTwo#2]

**Comment by hughest8** [comment]
• Number of  landmarks
• Number of treasures
o   Each hidden on a different landmark
• Set of traffic lights
o   Three settings
 Red
• Stop
 Amber
• Wait
 Green
• Go
• Start from a given point
• Robot should
o   Visit all landmarks where the treasures are hidden only once
o   Follow traffic lights until all treasures are found
• Treasures should
o   Display a message when found in forms of either
 Text
 Sound
 Image
• Landmarks should have
o   Name
o   Info on if treasure hidden
o   If robot has visited
• Treasure should have
o   ID
o   Name
