### ISSUE TITLE
Level Three

### ISSUE THREAD

**Issue by camerongough** [HolmesSquad/ProjectTwo#3]

**Comment by hughest8** [comment]
Level 3

• Number of  landmarks
• Number of treasures
o   Each hidden on a different landmarks
• Set of traffic lights
o   Three settings
 Red
• Stop
 Amber
• Wait
 Green
• Go
• 2 Robots
•  random starting points
• Robot should
o   Visit all landmarks where the treasures are hidden only once
o   Follow traffic lights until all treasures are found
o   Have a description of the given landmark
o   Move away from other robot
o   Move away from landmarks with have no treasure
• Treasures should
o   Display a message when found in forms of either
 Text
 Sound
 Image
o   Provide at least 100 points per pick up
• Landmarks should have
o   Name
o   Info on if treasure hidden
o   If robot has visited
o   Display information on the screen on the landmark if no treasure is hidden eg
 Text
 website
• Treasure should have
o   ID
o   Name
• A map should be incorporated into the background
• Other innovative features
o   Move the robot yourself telling you with landmarks to go to?
o   Arrows

**Comment by AlexHodson** [comment]
Level 3 is completed in my opinion:
2 Robots each with random starting points
4 Treasures with ID and points info
a number of landmarks each with an ID and info if a treasure is present
3 colours on traffic lights
the robots visit each landmark where a treasure is present
